import Head from "next/head";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { watchBlockNumber } from "@wagmi/core";
import { useEffect, useMemo, useState } from "react";
import { ethers, Signer } from "ethers";
import { constants } from "../constants";
import { useAccount, useProvider, useSigner } from "wagmi";
import Link from "next/link";
import { render_circles } from "../utils";
import SVG from "react-inlinesvg";

export default function Home() {
  const { address, isConnected } = useAccount();
  const [blockData, setBlockData] = useState<any>();
  const [caughtBlock, catchBlock] = useState<any>();
  const provider = useProvider();

  const { data: signer } = useSigner();
  const [svg, setSVG] = useState<string>();
  const contract = new ethers.Contract(
    constants.NFT_ADDRESS,
    constants.NFT_ABI
  );
  const caughtBlockSvg = useMemo(
    () => render_circles(caughtBlock?.hash),
    [blockData?.hash]
  );
  console.log(svg);
  useEffect(() => {
    const svg = render_circles(blockData?.hash);
    setSVG(svg);
  }, [blockData]);

  const getBlockData = async (blockNumber: number) => {
    try {
      const data = await provider.getBlock(blockNumber);
      setBlockData(data);
    } catch (error) {
      console.log(error);
    }
  };

  console.log(caughtBlockSvg);

  const mint = async () => {
    const tx = await contract
      .connect(signer as Signer)
      .mint(caughtBlock?.number, {
        value: ethers.utils.parseEther("0.001"),
        gasLimit: 10000000,
      });
    const result = await tx.wait();
    console.log(result);
  };

  useEffect(() => {
    watchBlockNumber(
      {
        chainId: 5,
        listen: true,
      },
      (blockNumber) => {
        getBlockData(blockNumber);
      }
    );
  }, []);
  console.log(blockData);
  return (
    <>
      <Head>
        <title>Color Hue State</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen">
        <header className="h-16 p-10 bg-black flex items-center justify-between">
          <Link className="ml-4" scroll={false} href="#about">
            <span className="text-white">about</span>
          </Link>
          <span className="mr-4">
            <ConnectButton />
          </span>
        </header>
        <section className="flex-grow bg-black parent-element grid place-items-center">
          <SVG
            style={{ top: "-300px" }}
            height="auto"
            width="100%"
            loader={<span>Loading...</span>}
            src={svg || ""}
            title={`Block #${blockData?.number}`}
          />
        </section>
        {!!caughtBlock && (
          <div className="w-400 h-400 absolute bottom-40 right-16 bg-black text-white border border-white rounded p-4 flex items-center">
            <button onClick={() => catchBlock(undefined)}>
              <svg
                className="mx-auto w-5 h-5 text-white cursor-pointer absolute top-2 right-2"
                viewBox="0 0 24 24"
                fill="currentColor"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M12 10.586l4.95-4.95 1.414 1.415-4.95 4.95 4.95 4.95-1.414 1.414-4.95-4.95-4.95 4.95-1.414-1.414 4.95-4.95-4.95-4.95L7.05 5.636l4.95 4.95z"></path>
              </svg>
            </button>
            <div className="relative">
              {/* <SVG
                className="absolute top-0 left-0 w-full h-auto"
                height="200"
                width="200"
                loader={<span>Loading...</span>}
                src={caughtBlockSvg || ""}
                title={`Block #${caughtBlock?.number}`}
              /> */}
              {`You chose Block #${caughtBlock?.number}`!}
              <br />
              <p>Ready to mint?</p>
              <br />
              <button
                onClick={() => {
                  mint();
                }}
                className="bg-transparent hover:bg-white text-white font-semibold hover:text-black py-2 px-4 border border-white hover:border-transparent rounded"
              >
                Mint
              </button>
            </div>
          </div>
        )}
        <section className="m-16 h-12 bg-black text-white">
          <div className="h-16 bg-black text-white flex items-center justify-between">
            <div className="mb-56">
              <p>
                Block # <span>{blockData?.number}</span>
              </p>
              <p>
                Hash #{" "}
                <span>
                  {blockData?.hash?.substring(0, 6)}
                  <br />
                  {blockData?.hash?.substring(6, 12)}
                  <br />
                  {blockData?.hash?.substring(12, 18)}
                  <br />
                  {blockData?.hash?.substring(18, 24)}
                  <br />
                  {blockData?.hash?.substring(24, 30)}
                  <br />
                  {blockData?.hash?.substring(30, 36)}
                  <br />
                  {blockData?.hash?.substring(36, 42)}
                  <br />
                  {blockData?.hash?.substring(42, 48)}
                  <br />
                  {blockData?.hash?.substring(48, 54)}
                  <br />
                  {blockData?.hash?.substring(54, 60)}
                  <br />
                  {blockData?.hash?.substring(60, 64)}
                </span>
              </p>
              <p>
                Time # <span>{blockData?.timestamp}</span>
              </p>
            </div>
            <div>
              {address && (
                <button
                  onClick={() => {
                    catchBlock(blockData);
                    // mint();
                  }}
                  className="bg-transparent hover:bg-white text-white font-semibold hover:text-black py-2 px-4 border border-white hover:border-transparent rounded"
                >
                  {!caughtBlock ? "Catch!" : "Catch new one!"}
                </button>
              )}
            </div>
          </div>
        </section>
      </div>
      <div className="flex flex-col h-screen">
        <section id="about" className="h-screen p-12 bg-black flex">
          <div className="w-1/2 p-4">
            <h2 className="text-xl text-white font-bold mb-4">ColorHueState</h2>
            <p className="text-white">
              ColorHueState is a cutting-edge digital art project that
              seamlessly blends the worlds of blockchain technology and visual
              aesthetics. Drawing inspiration from the dynamic and ever-evolving
              nature of the Ethereum blockchain, this immersive experience
              generates an exquisite symphony of chromatic circles, each
              representing the unique hues of the most recent Ethereum block
              hash. By tapping into the inherent randomness and unpredictability
              of blockchain data, ColorHueState is able to create a vivid and
              constantly changing visual tapestry. The result is a mesmerizing
              exploration of color, form, and movement that challenges
              traditional notions of digital artistry. <br /> <br /> Each circle
              embodies the essence of a singular moment in the Ethereum network,
              immortalizing it in a kaleidoscope of vibrant hues. As a testament
              to the beauty of decentralized networks, ColorHueState transcends
              the boundaries of conventional art, inviting viewers to ponder the
              intricate connections between technology and creativity. This
              compelling intersection of art and blockchain serves as a metaphor
              for the boundless potential of human innovation and our collective
              pursuit of harmony amidst chaos. ColorHueState is more than just
              an artistic display; it is an invitation to journey through the
              enigmatic world of blockchain, where every Ethereum block hash
              births a new, ephemeral masterpiece. Immerse yourself in the
              dynamic dance of colors, as ColorHueState captures the fluidity of
              the digital realm and transforms it into a visual symphony for the
              senses.
            </p>
          </div>
          <div className="w-1/2 p-4">
            {/* <h2 className="text-lg font-bold mb-4">Column 2</h2> */}
            <p className="text-white">
              As a testament to the beauty of decentralized networks,
              ColorHueState transcends the boundaries of conventional art,
              inviting viewers to ponder the intricate connections between
              technology and creativity. This compelling intersection of art and
              blockchain serves as a metaphor for the boundless potential of
              human innovation and our collective pursuit of harmony amidst
              chaos. <br /> <br /> ColorHueState is more than just an artistic
              display; it is an invitation to journey through the enigmatic
              world of blockchain, where every Ethereum block hash births a new,
              ephemeral masterpiece. Immerse yourself in the dynamic dance of
              colors, as ColorHueState captures the fluidity of the digital
              realm and transforms it into a visual symphony for the senses.
            </p>
          </div>
        </section>
        <footer className="h-16 bg-gray-900 text-white flex items-center justify-center">
          © {new Date().getFullYear()} Jurgen Ostarhild
        </footer>
      </div>
    </>
  );
}
